config/routes.rb
Obelisk::Application.routes.draw do

  resources :feedback_mails
  get "feedback", :controller => "feedback_mails", :action => "new", :as => "feedback"
  post "send_feedback", :controller => "feedback", :action => "send_feedback", :as =>"send_feedback"

  get "search", :controller => "search", :action => "search", :as=>"search"

  controller :sessions do
    get 'login' => :show_login_form, :as => 'login'
    post 'login' => :log_in
    delete 'logout' => :log_out
  end

  get "ritual_venki", :controller => "store", :action => "show_venki", :as=>"venki"
  get "ritual_korsinu", :controller => "store", :action => "show_korsinu", :as=>"korsinu"
  get "may_9", :controller => "store", :action => "show_may_9", :as=>"may_9"
  get "novinki", :controller => "store", :action => "show_novinki", :as=>"novinki"
  get "buy", :controller => "store", :action => "buy", :as=>"buy"
  get "calc", :controller => "store", :action => "calc", :as=>"calc"
  get "goods", :controller => "store", :action => "show_goods", :as=>"goods"

  resources :pages

  get ":page_ref", :controller => "pages", :action => "show_by_page_ref"

  root :controller => "pages", :action => "show_by_page_ref", :page_ref => 'about_us', :as => 'about_us'

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
    <% if @page.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

          <ul>
            <% @page.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label "Адрес страницы" %>
      <br/>
      <%= f.text_field :reference %>
    </div>

    <div class="field">
      <%= f.label "Имя страницы" %>
      <br/>
      <%= f.text_field :title %>
    </div>

    <%= fields_for :revision do |r| %>
        <script type="text/javascript">print_toolbar();</script>
        <%= r.text_area :content, :cols => 180, :rows => 20, :id => "f_text" %>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/pages/edit.html.erb
<h3>Редактирование страницы</h3>

<%= render 'form' %>

<%= link_to 'Показать', @page %> |
<%= link_to 'Назад', pages_path %>

app/views/pages/index.html.erb
<h3>Все страницы</h3>

<table id="pages-editor-table">
  <tr>
    <th>Адрес</th>
    <th>Имя страницы</th>
    <th>Номер ревизии</th>
    <th colspan="3">Управление</th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.reference %></td>
    <td><%= page.title %></td>
    <td><%= page.revisions.count %></td>
    <td class="manage"><%= link_to 'Показать', page %></td>
    <td class="manage"><%= link_to 'Редактировать', edit_page_path(page) %></td>
    <td class="manage"><%= link_to 'Удалить', page, :confirm => 'Вы уверены?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'Добавить страницу', new_page_path, :method => :get %>

app/views/pages/new.html.erb
<h3>Добавить страницу</h3>

<%= render 'form' %>

<%= link_to 'Назад', pages_path %>

app/views/pages/show.html.erb
<p>
  <b>Адрес:</b>
  <%= @page.reference %>
</p>

<p>
  <b>Имя страницы:</b>
  <%= @page.title %>
</p>

<p>
  <b>Содержание:</b>
  <%= @page.revisions.last.content %>
</p>

<br />

<%= link_to 'Редактировать', edit_page_path(@page) %> |
<%= link_to 'Назад', pages_path %>

app/views/pages/show_by_page_ref.html.erb
<div class="maincontent">

  <script src="/javascripts/jquery/jquery-1.6.1.min.js" type="text/javascript"></script>
  <script src="/javascripts/jquery/obelisk.js" type="text/javascript"></script>

  <script type='text/javascript'>
      jQuery.noConflict();
      hover_button("#back-link", "/images/back.png", "/images/go-back.png")
  </script>

  <%= raw @page.revisions.last.content %>

  <a id="back-link" href="javascript: history.go(-1)"><img src="/images/back.png" alt="Назад"/> Назад</a>

</div>