config/routes.rb
Obelisk::Application.routes.draw do

  resources :feedback_mails
  get "feedback", :controller => "feedback_mails", :action => "new", :as => "feedback"
  post "send_feedback", :controller => "feedback", :action => "send_feedback", :as =>"send_feedback"

  get "search", :controller => "search", :action => "search", :as=>"search"

  controller :sessions do
    get 'login' => :show_login_form, :as => 'login'
    post 'login' => :log_in
    delete 'logout' => :log_out
  end

  get "ritual_venki", :controller => "store", :action => "show_venki", :as=>"venki"
  get "ritual_korsinu", :controller => "store", :action => "show_korsinu", :as=>"korsinu"
  get "may_9", :controller => "store", :action => "show_may_9", :as=>"may_9"
  get "novinki", :controller => "store", :action => "show_novinki", :as=>"novinki"
  get "buy", :controller => "store", :action => "buy", :as=>"buy"
  get "calc", :controller => "store", :action => "calc", :as=>"calc"
  get "goods", :controller => "store", :action => "show_goods", :as=>"goods"

  resources :pages

  get ":page_ref", :controller => "pages", :action => "show_by_page_ref"

  root :controller => "pages", :action => "show_by_page_ref", :page_ref => 'about_us', :as => 'about_us'

end

app/models/feedback_mail.rb
# coding: utf-8

#Full access shared  model
class FeedbackMail < ActiveRecord::Base

  validates :email, :format => {
      :with => /.+/,
      :message => "Ваш почтовый ящик не указан "
  }

  validates :email, :email => true

  validates :name, :format => {
      :with => /.+/,
      :message => "Ваше имя не указано "
  }

  validates :message, :format => {
      :with => /.+/,
      :message => "Сообщение пустое"
  }

  validates :application_name, :presence => true

  before_create :setup_application_name
  before_update :verify_application_name
  before_destroy :verify_application_name
  after_find :verify_application_name

  private

  def setup_application_name()
    self.application_name=APPLICATION_NAME
  end

  def verify_application_name()
    unless self.application_name == APPLICATION_NAME
      raise "Permission denied to message " + self.id
    end
  end

end

app/controllers/feedback_mails_controller.rb
# coding: utf-8

class FeedbackMailsController < ApplicationController

  skip_before_filter :authorize, :only => [:new, :create]

  # GET /feedback_mails
  # GET /feedback_mails.xml
  def index
    @feedback_mails = FeedbackMail.find_all_by_application_name APPLICATION_NAME

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feedback_mails }
    end
  end

  # GET /feedback_mails/1
  # GET /feedback_mails/1.xml
  def show
    @feedback_mail = FeedbackMail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feedback_mail }
    end
  end

  # GET /feedback_mails/new
  # GET /feedback_mails/new.xml
  def new
    @feedback_mail = FeedbackMail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feedback_mail }
    end
  end

  # POST /feedback_mails
  # POST /feedback_mails.xml
  def create
    @feedback_mail = FeedbackMail.new(params[:feedback_mail])

    respond_to do |format|
      if @feedback_mail.save
      FeedbackMails.send_mail_now(@feedback_mail.email, @feedback_mail.name, @feedback_mail.phone, @feedback_mail.message).deliver
        format.html { redirect_to("/contacts", :notice => 'Сообщение отправлено') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # DELETE /feedback_mails/1
  # DELETE /feedback_mails/1.xml
  def destroy
    @feedback_mail = FeedbackMail.find(params[:id])
    @feedback_mail.destroy

    respond_to do |format|
      format.html { redirect_to(feedback_mails_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/feedback_mails_helper.rb
module FeedbackMailsHelper
end

app/views/feedback_mails/_form.html.erb
<div class="maincontent">

  <script src="/javascripts/jquery/jquery-1.6.1.min.js" type="text/javascript"></script>
  <script src="/javascripts/jquery/obelisk.js" type="text/javascript"></script>

  <script type='text/javascript'>
      jQuery.noConflict();
      hover_button("#back-link", "/images/back.png", "/images/go-back.png")
  </script>

  <h3>Отправить сообщение</h3>

  <%= form_for(@feedback_mail) do |f| %>
      <% if @feedback_mail.errors.any? %>
          <div id="error_explanation">
            <h2>Сообщение не может быть отправлено:</h2>
            <ul>
              <% @feedback_mail.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= label_tag "Ваш почтовый ящик *" %>
        <br/>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= label_tag "Ваше имя *" %>
        <br/>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= label_tag "Телефон" %>
        <br/>
        <%= f.text_field :phone %>
      </div>
      <div class="field">
        <%= label_tag "Сообщение" %>
        <br/>
        <%= f.text_area :message, :rows=>20, :cols=>113 %>
      </div>
      <div class="actions">
        <%= f.submit 'Отправить' %>
      </div>
  <% end %>

  <a id="back-link" href="javascript: history.go(-1)"><img src="/images/back.png" alt="Назад"/> Назад</a>

</div>

app/views/feedback_mails/index.html.erb
<h3>Listing feedback_mails</h3>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Phone</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedback_mails.each do |feedback_mail| %>
  <tr>
    <td><%= feedback_mail.email %></td>
    <td><%= feedback_mail.name %></td>
    <td><%= feedback_mail.phone %></td>
    <td><%= link_to 'Show', feedback_mail %></td>
    <td><%= link_to 'Destroy', feedback_mail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback mail', new_feedback_mail_path %>

app/views/feedback_mails/new.html.erb
<%= render 'form' %>

app/views/feedback_mails/send_mail_now.html.erb
<%= @feedback_msg %>
<br/>
<hr>
<i>
Почтовый ящик пользователя:<br/>
<%= @sender_mail %>
<br/>
Телефон:
<%= @sender_phone %>
</i>

app/views/feedback_mails/show.html.erb
<div class="maincontent">

  <script src="/javascripts/jquery/jquery-1.6.1.min.js" type="text/javascript"></script>
  <script src="/javascripts/jquery/obelisk.js" type="text/javascript"></script>

  <script type='text/javascript'>
      jQuery.noConflict();
      hover_button("#back-link", "/images/back.png", "/images/go-back.png")
  </script>

  <h3>Cообщение</h3>

  <p>
    <b>Email:</b>
    <%= @feedback_mail.email %>
  </p>

  <p>
    <b>Name:</b>
    <%= @feedback_mail.name %>
  </p>

  <p>
    <b>Phone:</b>
    <%= @feedback_mail.phone %>
  </p>

  <p>
    <b>Message:</b>
    <%= @feedback_mail.message %>
  </p>


  <a id="back-link" href="javascript: history.go(-1)"><img src="/images/back.png" alt="Назад"/> Назад</a>
</div>