config/routes.rb
Obelisk::Application.routes.draw do

  resources :feedback_mails
  get "feedback", :controller => "feedback_mails", :action => "new", :as => "feedback"
  post "send_feedback", :controller => "feedback", :action => "send_feedback", :as =>"send_feedback"

  get "search", :controller => "search", :action => "search", :as=>"search"

  controller :sessions do
    get 'login' => :show_login_form, :as => 'login'
    post 'login' => :log_in
    delete 'logout' => :log_out
  end

  get "ritual_venki", :controller => "store", :action => "show_venki", :as=>"venki"
  get "ritual_korsinu", :controller => "store", :action => "show_korsinu", :as=>"korsinu"
  get "may_9", :controller => "store", :action => "show_may_9", :as=>"may_9"
  get "novinki", :controller => "store", :action => "show_novinki", :as=>"novinki"
  get "buy", :controller => "store", :action => "buy", :as=>"buy"
  get "calc", :controller => "store", :action => "calc", :as=>"calc"
  get "goods", :controller => "store", :action => "show_goods", :as=>"goods"

  resources :pages

  get ":page_ref", :controller => "pages", :action => "show_by_page_ref"

  root :controller => "pages", :action => "show_by_page_ref", :page_ref => 'about_us', :as => 'about_us'

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta name="Description"
        content="Оптовая розничная продажа ритуальных траурных венков и корзин по России."/>
  <meta name="Keywords" content="траурные,ритуальные,венки,россия"/>
  <meta name="robots" content="all,follow"/>
  <meta http-equiv="Content-Script-Type" content="text/javascript"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

  <%= stylesheet_link_tag :all, :recursive => false, :cache => false %>
  <%= javascript_include_tag :all, :recursive => false, :cache => false %>
<!--[if IE 7]>
    <link href="/stylesheets/IE/ie7_fixes.css" media="screen" rel="stylesheet" type="text/css"/>
<![endif]-->
<!--[if lte IE 6]>
    <link href="/stylesheets/IE/ie6_fixes.css" media="screen" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="/javascripts/IE/unitpngfix.js"></script>
<![endif]-->  
  <%= csrf_meta_tag %>

  <title>Траурные ритуальные венки и корзины. Оптовая и розничная продажа по России</title>
</head>
<body>
<div id="main">
  <div id="header">
    <ul id="navigation">
      <% if session[:admin] %>
          <li id="house"><%= link_to 'Выйти', logout_path, :method => :delete %></li>
          <li id="sitemap"><%= link_to 'Страницы', pages_path %></li>
          <li id="sitemap"><%= link_to 'Сообщения', feedback_mails_path %></li>
      <% else %>
          <li id="house"><%= link_to 'Войти в систему', login_path %></li>
      <% end %>
    </ul>

    <img src="/images/logo.png" alt="obelisk" id="logo"/>

    <h1><a href="/about_us">Траурные ритуальные венки и корзины</a></h1>

    <h2 class="new"><a href="http://www.venki-spb.ru">Открыт интернет-магазин в Спб!</a></h2>

    <h2 class="new">&nbsp;</h2>

    <div class="order-phone1">
      <a href="/contacts">Опт:&nbsp;+7(911) 100-07-00</a>
    </div>

    <div class="order-phone2">
      <!--<a href="/contacts">Розница:&nbsp;+7(911) 127-71-77</a>-->
      <a href="http://www.venki-spb.ru">Розница:&nbsp;www.venki-spb.ru</a>
    </div>

    <div class="order-phone3">
      <a href="http://www.venki-spb.ru">+7(911) 127-71-77</a>
    </div>


    <ul id="menu">
      <%= raw tab_list_raw %>
    </ul>
  </div>

  <hr class="noscreen"/>

  <div id="content">
    <%= raw print_notice(notice) %>
    <%= yield %>
  </div>

  <hr class="noscreen"/>

  <div class="cleaner">&nbsp;</div>

  <div id="footer">
    ПК Венок 2009-2013
  </div>
</div>
<%= render :file => '/layouts/_counters.html' %>
</body>
</html>